package com.airline.iotdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Alert implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Alert() {
    }




}