package com.airline.iotdemo;

import org.kie.api.definition.type.Label;
import org.kie.api.definition.type.Description;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Label("FOODTRUCK")
@Description("A Food Truck")
public class Cart implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@Label("TRUCK ID")
	@Description("Truck ID")
	private String id;

	@Description(value = "Current Date")
	@Label(value = "CURRENTDATE")
	private Long timestamp;

	@Label("LOCLATITUDE")
	@Description("Geolocation Latitude")
	private Double latitude;

	@Label("LOCLONGITUDE")
	@Description("Geolocation Longitude")
	private Double longitude;

	@Label("TEMPSENSORVALUE")
	@Description("Temperature Sensor Value")
	private Double temperature;

	@Label("RFID")
	@Description("Food Container RFID")
	private String foodId;

	@Label("STATUS")
	@Description("Cart Status")
	private Integer status;

	public Cart() {
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Long timestamp) {
		this.timestamp = timestamp;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Double temperature) {
		this.temperature = temperature;
	}

	public String getFoodId() {
		return this.foodId;
	}

	public void setFoodId(String foodId) {
		this.foodId = foodId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Cart(String id, Long timestamp, Double latitude, Double longitude,
	        	Double temperature, String foodId, Integer status) {
		this.latitude = latitude;
		this.longitude = longitude;
		this.temperature = temperature;
		this.id = id;
		this.foodId = foodId;
		this.status = status;
		this.timestamp = timestamp;
	}

}