package com.airline.iotdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Cart")
@org.kie.api.definition.type.Description("A food cart")
public class Cart implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Trays")
	@org.kie.api.definition.type.Description("Collection of food trays in the food cart")
	private java.util.List<com.airline.iotdemo.Tray> trays;

	@org.kie.api.definition.type.Description(value = "Type of cart.")
	@org.kie.api.definition.type.Label(value = "Type")
	private java.lang.String type;

	public Cart() {
	}

	public java.util.List<com.airline.iotdemo.Tray> getTrays() {
		return this.trays;
	}

	public void setTrays(java.util.List<com.airline.iotdemo.Tray> trays) {
		this.trays = trays;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public Cart(java.util.List<com.airline.iotdemo.Tray> trays,
			java.lang.String type) {
		this.trays = trays;
		this.type = type;
	}

}