package com.airline.iotdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("FOODTRUCK")
@org.kie.api.definition.type.Description("A Food Truck")
public class Cart implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("LOCLATITUDE")
	@org.kie.api.definition.type.Description("Geolocation Latitude")
	private Double latitude;

	@org.kie.api.definition.type.Label("LOCLONGITUDE")
	@org.kie.api.definition.type.Description("Geolocation Longitude")
	private Double longitude;

	@org.kie.api.definition.type.Label("TEMPSENSORVALUE")
	@org.kie.api.definition.type.Description("Temperature Sensor Value")
	private java.lang.Double temperature;

	@org.kie.api.definition.type.Label("TRUCK ID")
	@org.kie.api.definition.type.Description("Truck ID")
	private java.lang.String id;

	@org.kie.api.definition.type.Label("RFID")
	@org.kie.api.definition.type.Description("Food Container RFID")
	private java.lang.String foodId;

	@org.kie.api.definition.type.Label("STATUS")
	@org.kie.api.definition.type.Description("Cart Status")
	private java.lang.Integer status;

	@org.kie.api.definition.type.Description(value = "Current Date")
	@org.kie.api.definition.type.Label(value = "CURRENTDATE")
	private java.lang.Long timestamp;

	public Cart() {
	}

	public java.lang.Double getTemperature() {
		return this.temperature;
	}

	public void setTemperature(java.lang.Double temperature) {
		this.temperature = temperature;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(java.lang.Double latitude) {
		this.latitude = latitude;
	}

	public java.lang.Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(java.lang.Double longitude) {
		this.longitude = longitude;
	}

	public java.lang.String getFoodId() {
		return this.foodId;
	}

	public void setFoodId(java.lang.String foodId) {
		this.foodId = foodId;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.lang.Long getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(java.lang.Long timestamp) {
		this.timestamp = timestamp;
	}

	public Cart(java.lang.Double latitude, java.lang.Double longitude,
			java.lang.Double temperature, java.lang.String id,
			java.lang.String foodId, java.lang.Integer status,
			java.lang.Long timestamp) {
		this.latitude = latitude;
		this.longitude = longitude;
		this.temperature = temperature;
		this.id = id;
		this.foodId = foodId;
		this.status = status;
		this.timestamp = timestamp;
	}

}