package com.airline.iotdemo;

import org.kie.api.definition.type.Label;
import org.kie.api.definition.type.Description;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("FOODCONTAINER")
@org.kie.api.definition.type.Description("Food Container")
public class Food implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("RFIDTYPE")
	@org.kie.api.definition.type.Description("Food type RFID.")
	private String type;

	@org.kie.api.definition.type.Description("Food RFID.")
	@org.kie.api.definition.type.Label("RFID")
	private String rfid;

	@org.kie.api.definition.type.Description(value = "Food name.")
	private java.lang.String name;

	public Food() {
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRfid() {
		return this.rfid;
	}

	public void setRfid(String rfid) {
		this.rfid = rfid;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Food(java.lang.String type, java.lang.String rfid,
			java.lang.String name) {
		this.type = type;
		this.rfid = rfid;
		this.name = name;
	}

}
