package com.airline.iotdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("FOODCONTAINER")
@org.kie.api.definition.type.Description("Food Container")
public class Food implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("RFIDTYPE")
	@org.kie.api.definition.type.Description("Type of food.")
	private java.lang.String type;

	@org.kie.api.definition.type.Description("Food RFID")
	@org.kie.api.definition.type.Label("RFID")
	private java.lang.String rfid;

	public Food() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getRfid() {
		return this.rfid;
	}

	public void setRfid(java.lang.String rfid) {
		this.rfid = rfid;
	}

	public Food(java.lang.String type, java.lang.String rfid) {
		this.type = type;
		this.rfid = rfid;
	}

}