package com.airline.iotdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Tray")
@org.kie.api.definition.type.Description("A food tray")
public class Tray implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public Tray() {
	}

}